services:
  traefik:
    image: traefik:v3.6.2
    restart: unless-stopped
    command:
      - --providers.file.filename=/etc/traefik/dynamic.yml
      - --providers.file.watch=true
      - --entrypoints.websecure.address=:3443
      - --log.level=INFO
      - --accesslog=true
    network_mode: host
    volumes:
      - ./traefik/dynamic.yml:/etc/traefik/dynamic.yml:ro
      - ./certs:/certs:ro
